spring:
  datasource:
    url: jdbc:h2:mem:deliverydb
    driver-class-name: org.h2.Driver
    username: hwu
    password: password-hwu
    schema: classpath:schema.sql
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080


logging:
  level:
    root: INFO
    org.springframework: WARN
    com.ahold.ctp.assignment: DEBUG


swagger:
  api:
    title: Delivery System
    description: APIs for Delivery System
    version: 1.0
    contact:
      name: Huiyao Wu